import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <nav className="bg-gray-900 shadow mb-8 p-4 flex gap-6 items-center">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-white font-bold text-lg tracking-wide">🎬 RecoWatch</span>
          </Link>
          <Link href="/profile" className="ml-auto">
            <span className="inline-flex w-10 h-10 rounded-full bg-gray-800 items-center justify-center text-2xl text-white hover:bg-gray-700 transition">👤</span>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
